version: '3.9'

volumes:
  local_data: {}

services:
  dj:
    container_name: tuto_dj
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes: 
      - ./.env:/tuto/.env
    ports:
      - ${PORT}:8000
    working_dir: /REST/
    command: sh /REST/start.sh
    stdin_open: true
    tty: true
